# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours

  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generates the Snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: SAditi03  # Replace with your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show git status (for debugging)
      - name: Show Git Status
        run: git status

      # Push the changes to the 'output' branch
      - name: Push Changes
        uses: actions-x/commit@v6
        with:
          message: "Update snake animation"
          branch: output  # Ensure this branch exists
          force: true

      # Deploy to GitHub Pages (if needed)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
